<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-button_Search</name>
   <tag></tag>
   <elementGuidId>d22515a5-3f40-4110-a18d-e8132756b9ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-router-outlet[@id='main-content']/app-appointment-table/ion-content/div/div/ion-grid/ion-row/ion-grid/ion-row/ion-col/ion-grid/ion-row/ion-col[2]/form/ion-grid/ion-row/ion-col[3]/ion-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pin-search-btn md button button-solid ion-activatable ion-focusable hydrated ion-activated</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Search </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-appointment-table[@class=&quot;ng-star-inserted ion-page can-go-back&quot;]/ion-content[@class=&quot;md hydrated&quot;]/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;register-wrap&quot;]/ion-grid[@class=&quot;padding-0 md hydrated&quot;]/ion-row[@class=&quot;md hydrated&quot;]/ion-grid[@class=&quot;padding-0 ng-star-inserted md hydrated&quot;]/ion-row[@class=&quot;md hydrated&quot;]/ion-col[@class=&quot;register-box md hydrated&quot;]/ion-grid[@class=&quot;md hydrated&quot;]/ion-row[@class=&quot;md hydrated&quot;]/ion-col[@class=&quot;md hydrated&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/ion-grid[@class=&quot;md hydrated&quot;]/ion-row[@class=&quot;md hydrated&quot;]/ion-col[@class=&quot;col-padding ion-text-start ng-star-inserted md hydrated&quot;]/ion-button[@class=&quot;pin-search-btn md button button-solid ion-activatable ion-focusable hydrated ion-activated&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/app-appointment-table/ion-content/div/div/ion-grid/ion-row/ion-grid/ion-row/ion-col/ion-grid/ion-row/ion-col[2]/form/ion-grid/ion-row/ion-col[3]/ion-button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your PIN'])[1]/following::ion-button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Appointment for Vaccination'])[1]/following::ion-button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-col[3]/ion-button</value>
   </webElementXpaths>
</WebElementEntity>
